# Generated by Django 5.2.4 on 2025-08-25 03:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(help_text='The scheduled date of arrival')),
                ('check_out_date', models.DateField(help_text='The scheduled date of departure')),
                ('number_of_adults', models.PositiveIntegerField(default=1, help_text='The number of adults for the booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_children', models.PositiveIntegerField(default=0, help_text='The number of children for the booking', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELED', 'Canceled'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending')], default='CONFIRMED', help_text='The status of the booking', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='The calculated total cost of the room for the stay', max_digits=10)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or notes for the booking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(help_text='The guest making this booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guest.guest')),
                ('room', models.ForeignKey(help_text='The room being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='check_out_after_check_in')],
            },
        ),
    ]
