# Generated by Django 5.2.4 on 2025-08-26 14:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('guest', '0001_initial'),
        ('rate', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_check_in_time',
            field=models.DateTimeField(blank=True, help_text='Actual check-in date and time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_check_out_time',
            field=models.DateTimeField(blank=True, help_text='Actual check-out date and time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance payment received', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_notes',
            field=models.TextField(blank=True, help_text='Internal booking notes', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('OTA', 'Online Travel Agency'), ('AGENT', 'Travel Agent'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WALK_IN', 'Walk-in'), ('CORPORATE', 'Corporate'), ('WEBSITE', 'Website')], default='DIRECT', help_text='Booking Source (direct, OTA, agent)', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_number',
            field=models.CharField(blank=True, help_text='External confirmation number (for OTA bookings)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial Payment'), ('PAID', 'Fully Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='rate_plan',
            field=models.ForeignKey(blank=True, help_text='Rate Plan applied to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rate.rateplan'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(help_text='Check-in Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(help_text='Check-out Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(help_text='Guest ID or details', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guest.guest'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=1, help_text='Number of adults', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0, help_text='Number of children', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(help_text='Room Type and Number', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Special Requests', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELED', 'Canceled'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending')], default='CONFIRMED', help_text='Reservation Status (confirmed, pending, cancelled)', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total booking amount', max_digits=10),
        ),
    ]
