# Generated by Django 5.2.4 on 2025-08-27 03:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_actual_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text='Unique corporate/agent identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Corporate/Agent name', max_length=150)),
                ('agent_type', models.CharField(choices=[('CORPORATE', 'Corporate Client'), ('AGENT', 'Travel Agent'), ('TOUR_OPERATOR', 'Tour Operator'), ('EVENT_PLANNER', 'Event Planner'), ('WEDDING_PLANNER', 'Wedding Planner'), ('OTHER', 'Other')], default='CORPORATE', help_text='Type of corporate client or agent', max_length=20)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=100)),
                ('designation', models.CharField(blank=True, help_text='Contact person designation', max_length=100, null=True)),
                ('address', models.TextField(help_text='Complete address')),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20)),
                ('mobile', models.CharField(blank=True, help_text='Mobile number', max_length=20, null=True)),
                ('email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('business_registration', models.CharField(blank=True, help_text='Business registration number', max_length=50, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GSTIN (if applicable)', max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number', max_length=10, null=True)),
                ('contracted_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Special contracted rate per night', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission rate percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit limit amount', max_digits=12)),
                ('payment_terms', models.CharField(choices=[('IMMEDIATE', 'Immediate Payment'), ('NET_7', 'Net 7 Days'), ('NET_15', 'Net 15 Days'), ('NET_30', 'Net 30 Days'), ('NET_45', 'Net 45 Days'), ('NET_60', 'Net 60 Days'), ('ADVANCE', 'Advance Payment Required')], default='NET_30', help_text='Payment terms', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this corporate/agent is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporate/Agent',
                'verbose_name_plural': 'Corporate/Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(help_text='Unique source identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Source name (e.g., Booking.com, Expedia, Company Website)', max_length=100)),
                ('source_type', models.CharField(choices=[('OTA', 'Online Travel Agency'), ('WEBSITE', 'Website'), ('AGENT', 'Travel Agent'), ('CORPORATE', 'Corporate'), ('DIRECT', 'Direct'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WALK_IN', 'Walk-in'), ('OTHER', 'Other')], default='OTHER', help_text='Type of reservation source', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Contact address', null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission rate percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is currently active')),
                ('website_url', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reservation Source',
                'verbose_name_plural': 'Reservation Sources',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='corporate_agent',
            field=models.ForeignKey(blank=True, help_text='Corporate client or travel agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.corporateagent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_source',
            field=models.ForeignKey(blank=True, help_text='Reservation source (OTA, website, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.reservationsource'),
        ),
    ]
