# Generated by Django 5.2.4 on 2025-08-27 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(help_text='Unique service identifier', max_length=20, unique=True)),
                ('service_name', models.CharField(help_text='Service name (e.g., Spa, Laundry, Room Service)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the service', null=True)),
                ('rate_cost', models.DecimalField(decimal_places=2, help_text='Service rate/cost in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_applicable', models.BooleanField(default=True, help_text='Whether tax is applicable on this service')),
                ('availability', models.CharField(choices=[('24_7', '24/7 Available'), ('BUSINESS_HOURS', 'Business Hours Only'), ('WEEKDAYS', 'Weekdays Only'), ('WEEKENDS', 'Weekends Only'), ('CUSTOM', 'Custom Hours')], default='BUSINESS_HOURS', help_text='Service availability schedule', max_length=20)),
                ('available_from', models.TimeField(blank=True, help_text='Service available from (for custom hours)', null=True)),
                ('available_to', models.TimeField(blank=True, help_text='Service available until (for custom hours)', null=True)),
                ('available_days', models.CharField(blank=True, help_text='Available days (for custom schedule)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently active')),
                ('requires_booking', models.BooleanField(default=False, help_text='Whether this service requires advance booking')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity/slots available (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
    ]
