# Generated by Django 5.2.4 on 2025-08-28 14:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_corporateagent_reservationsource_and_more'),
        ('guest', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the service', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of billing', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Tax rate percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total bill amount including tax', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('BILLED', 'Billed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='BILLED', help_text='Current payment status of this charge', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Associated booking, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_charges', to='booking.booking')),
                ('guest', models.ForeignKey(help_text='Guest to bill', on_delete=django.db.models.deletion.PROTECT, related_name='service_charges', to='guest.guest')),
                ('service', models.ForeignKey(help_text='Which service is being billed', on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='service.service')),
            ],
            options={
                'verbose_name': 'Service Charge',
                'verbose_name_plural': 'Service Charges',
                'ordering': ['-created_at'],
            },
        ),
    ]
