# Generated by Django 5.2.4 on 2025-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Amenity Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity_limit', models.PositiveIntegerField(blank=True, help_text='Leave blank if not applicable', null=True, verbose_name='Quantity/Limit')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
    ]
