# Generated by Django 5.2.4 on 2025-08-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='applicable_room_types',
            field=models.ManyToManyField(blank=True, related_name='applicable_amenities', to='rooms.roomtype', verbose_name='Applicable Room Types'),
        ),
    ]
