# Generated by Django 5.2.4 on 2025-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0002_initial'),
        ('service', '0002_servicecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='base_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base charge for this amenity (if chargeable)', max_digits=10, null=True, verbose_name='Base Charge (₹)'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_chargeable',
            field=models.BooleanField(default=False, help_text='Check if this amenity has associated charges', verbose_name='Chargeable Amenity'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text='Services associated with this amenity', related_name='amenities', to='service.service', verbose_name='Related Services'),
        ),
    ]
