# Generated by Django 5.2.4 on 2025-09-01 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_corporateagent_reservationsource_and_more'),
        ('guest', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_id', models.CharField(help_text='Unique check-in identifier', max_length=20, unique=True)),
                ('actual_check_in_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Actual date and time of check-in')),
                ('id_proof_verified', models.BooleanField(default=False, help_text="Whether guest's ID proof has been verified")),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial Payment'), ('PAID', 'Fully Paid'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current payment status', max_length=10)),
                ('assigned_staff', models.CharField(blank=True, help_text='Staff member who handled the check-in', max_length=100, null=True)),
                ('remarks_notes', models.TextField(blank=True, help_text='Additional remarks or notes about the check-in', null=True)),
                ('expected_check_out_date', models.DateField(blank=True, help_text='Expected check-out date', null=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1, help_text='Total number of guests checking in')),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0.0, help_text='Advance payment received', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount for the stay', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Associated booking (if pre-booked)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='booking.booking')),
                ('guest', models.ForeignKey(help_text='Primary guest checking in', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='guest.guest')),
                ('room_number', models.ForeignKey(help_text='Room assigned for check-in', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Check-In',
                'verbose_name_plural': 'Check-Ins',
                'ordering': ['-actual_check_in_date_time'],
            },
        ),
    ]
